### ISSUE TITLE
Error: panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by jouni** [errata-ai/vale-action#76] opened 2022-09-30 06:01 UTC
We’ve been getting this error in multiple pull requests recently, and I’m not sure why.

https://github.com/vaadin/docs/actions/runs/3156575828/jobs/5136429971/#step:4:1

<img width="1098" alt="Screenshot 2022-09-30 at 9 01 18" src="https://user-images.githubusercontent.com/66382/193200823-465944d5-ffd7-4795-9f99-245e78858d0b.png">

**Comment by jdkato** [comment] 2022-09-30 20:49
This looks like a bug with Vale (not the action itself). Does it also occur locally?

**Comment by jdkato** [comment] 2022-10-01 08:23
I tried briefly and I couldn't reproduce this using your local configuration. So, it's probably something that was fixed in a more recent version of Vale.

You may want to consider updating to the Reviewdog-based action, which supports the latest version of Vale.

**Comment by jouni** [comment] 2022-10-01 12:06
Thanks for looking into it! No problems running locally. 

I'll try updating to the new action.

**Comment by jouni** [comment] 2022-10-03 07:01
The reviewdog-based action works nicely. Though, I’m having trouble using the `--config` option, fails with “path does not exists”.

This works locally:

```sh
vale --config='.vale-pr.ini' .
```

But this fails with the GitHub action:

```yaml
vale_flags: "--config='.vale-pr.ini'"
```

Update: I tried the following variations:

```
--config='${GITHUB_WORKSPACE}/.vale-pr.ini'
--config='$GITHUB_WORKSPACE/.vale-pr.ini'
--config='${{env.GITHUB_WORKSPACE}}/.vale-pr.ini'
--config='${{github.workspace}}/.vale-pr.ini'
```

No luck. I’m not very familiar with the correct syntax I should use here.

The last one seems like it should work, as it produces this command (though I wonder about the duplicate `docs` there), but it still fails the same: 

```sh
/github/home/vale --config='/home/runner/work/docs/docs/.vale-pr.ini'
```

**Comment by jdkato** [comment] 2022-10-05 21:23
Does it work if you remove the extra quotes?

```yaml
vale_flags: "--config=.vale-pr.ini"
```

**Comment by jouni** [comment] 2022-10-06 12:04
Yes, looks like that works. Thanks! I should have realized to try that as well.

**Closed as completed** 2022-10-06 20:54 UTC
Labels: bug
